name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: install dependency
      run: |
        sudo apt install libncurses-dev -y
        sudo apt install cpio -y
        sudo apt install rsync -y
        sudo apt install bc -y
        sudo apt install gcc-multilib -y
        sudo apt install g++-multilib -y
    - name: show version
      run: |
        gcc --version
        g++ --version
        make --version
    - name: make
      run: make
