name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependency
      run: \
        apt install libncurses-dev -y
        apt install cpio -y
        apt install rsync -y
        apt install bc -y
        apt install gcc-multilib -y
        apt install g++-multilib -y
    - name: make
      run: make
